use eanprod;
SELECT airportcoordinateslist.AirportCode, airportcoordinateslist.AirportName, citycoordinateslist.RegionName
FROM airportcoordinateslist INNER JOIN citycoordinateslist ON airportcoordinateslist.MainCityID = citycoordinateslist.RegionID;